id: P97C23560
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4860
  instance_id: http://purl.bdrc.io/resource/IE1KG4860
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - དགག་ལན་སྤྲིན་གྱི་སྒྲ་དབྱངས།
  alt_title:
    en-x-mixed:
    - Dgag lan sprin gyi sgra dbyaṅs /ʼBaʼ Don-grub-rgyal gyis brtsams.
    zh-latn-pinyin-x-ndia:
    - xiang bian zhi lie sheng
  author: http://purl.bdrc.io/resource/P8057
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    ddd5db8140c74fd9b4fa6547454b7bd8:
      title: པོད ༡་དགག་ལན་སྤྲིན་གྱི་སྒྲ་དབྱངས
      volume_number: 1
      base_file: UT1KG4860_I1KG5021_0000.txt
      reference: http://purl.bdrc.io/resource/VLBED9CCEC0E2F59D7
      image_group: I1KG5021
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4860
  - http://purl.bdrc.io/resource/W1KG4860
  ocr_software: Namsel
created_at: '2021-12-22T10:44:25.014014'
last_modified_at: '2021-12-22T10:44:25.014020'
